-- Create complaints table
CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  location TEXT NOT NULL,
  ward TEXT DEFAULT '',
  description TEXT,
  status TEXT DEFAULT 'submitted',
  photo_url TEXT,
  resolved_photo_url TEXT,
  user_id TEXT,
  reporter_name TEXT DEFAULT 'Anonymous',
  reporter_phone TEXT DEFAULT '',
  reporter_email TEXT DEFAULT '',
  assigned_to TEXT DEFAULT '',
  admin_notes JSONB DEFAULT '[]'::jsonb,
  upvotes INTEGER DEFAULT 0,
  upvoted_by JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: We are using JSONB for admin_notes and upvoted_by to store arrays/objects
-- This replaces the TEXT arrays stored as JSON strings in SQLite.
